version: "3.9"

services:
  api:
    build: ./{{cookiecutter.project_slug}}/
    environment:
      - API_HOST=api
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/src
    volumes:
      - ./{{cookiecutter.project_slug}}/src:/src
      - ./{{cookiecutter.project_slug}}/tests:/tests
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
      
  db:
    container_name: postgresql_db
    image: postgres:14.2-bullseye
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data: null
